// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DatabaseBackupInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Name of the logical database within the DBaaS cluster to back up.
	// Name of the logical database within the DBaaS cluster to back up.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) ID of the DBaaS cluster or database to back up.
	// ID of the DBaaS cluster or database to back up.
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Availability zone within the region where the backup is stored.
	// Availability zone within the region where the backup is stored.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DatabaseBackupObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Name of the logical database within the DBaaS cluster to back up.
	// Name of the logical database within the DBaaS cluster to back up.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) ID of the DBaaS cluster or database to back up.
	// ID of the DBaaS cluster or database to back up.
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// generated backup name assigned by the API (e.g. mysql_wordpress_20260713140736). The value provided in config is not used — the API always generates its own name.
	// Auto-generated backup name assigned by the API (e.g. `mysql_wordpress_20260713140736`). The value provided in config is not used — the API always generates its own name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) Availability zone within the region where the backup is stored.
	// Availability zone within the region where the backup is stored.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DatabaseBackupParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Required
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Name of the logical database within the DBaaS cluster to back up.
	// Name of the logical database within the DBaaS cluster to back up.
	// +kubebuilder:validation:Required
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) ID of the DBaaS cluster or database to back up.
	// ID of the DBaaS cluster or database to back up.
	// +kubebuilder:validation:Required
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Availability zone within the region where the backup is stored.
	// Availability zone within the region where the backup is stored.
	// +kubebuilder:validation:Required
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// DatabaseBackupSpec defines the desired state of DatabaseBackup
type DatabaseBackupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DatabaseBackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabaseBackupInitParameters `json:"initProvider,omitempty"`
}

// DatabaseBackupStatus defines the observed state of DatabaseBackup.
type DatabaseBackupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatabaseBackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DatabaseBackup is the Schema for the DatabaseBackups API. Manages a backup of an ArubaCloud DBaaS database.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,arubacloud}
type DatabaseBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dbaasId) || (has(self.initProvider) && has(self.initProvider.dbaasId))",message="spec.forProvider.dbaasId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DatabaseBackupSpec   `json:"spec"`
	Status DatabaseBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseBackupList contains a list of DatabaseBackups
type DatabaseBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DatabaseBackup `json:"items"`
}

// Repository type metadata.
var (
	DatabaseBackup_Kind             = "DatabaseBackup"
	DatabaseBackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DatabaseBackup_Kind}.String()
	DatabaseBackup_KindAPIVersion   = DatabaseBackup_Kind + "." + CRDGroupVersion.String()
	DatabaseBackup_GroupVersionKind = CRDGroupVersion.WithKind(DatabaseBackup_Kind)
)

func init() {
	SchemeBuilder.Register(&DatabaseBackup{}, &DatabaseBackupList{})
}
