apiVersion: dbaasuser.arubacloud.m.crossplane.io/v1alpha1
kind: DBaaSUser
metadata:
  annotations:
    meta.upbound.io/example-id: dbaasuser/v1alpha1/dbaasuser
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    dbaasId: example-dbaas-id
    passwordSecretRef:
      key: example-key
      name: example-secret
    username: example-user
