// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PropertiesInitParameters struct {

	// (String) Direction of the rule (Ingress/Egress)
	// Direction of the rule (Ingress/Egress)
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// (String) Port or port range (for TCP/UDP)
	// Port or port range (for TCP/UDP)
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol (ANY, TCP, UDP, ICMP)
	// Protocol (ANY, TCP, UDP, ICMP)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (Attributes) Target of the rule (source or destination) (see below for nested schema)
	Target *TargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type PropertiesObservation struct {

	// (String) Direction of the rule (Ingress/Egress)
	// Direction of the rule (Ingress/Egress)
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// (String) Port or port range (for TCP/UDP)
	// Port or port range (for TCP/UDP)
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol (ANY, TCP, UDP, ICMP)
	// Protocol (ANY, TCP, UDP, ICMP)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (Attributes) Target of the rule (source or destination) (see below for nested schema)
	Target *TargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type PropertiesParameters struct {

	// (String) Direction of the rule (Ingress/Egress)
	// Direction of the rule (Ingress/Egress)
	// +kubebuilder:validation:Optional
	Direction *string `json:"direction" tf:"direction,omitempty"`

	// (String) Port or port range (for TCP/UDP)
	// Port or port range (for TCP/UDP)
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol (ANY, TCP, UDP, ICMP)
	// Protocol (ANY, TCP, UDP, ICMP)
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// (Attributes) Target of the rule (source or destination) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Target *TargetParameters `json:"target" tf:"target,omitempty"`
}

type SecurityRuleInitParameters struct {

	// (String) Security Rule location
	// Security Rule location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Security Rule name
	// Security Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this Security Rule belongs to
	// ID of the project this Security Rule belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Properties of the security rule (see below for nested schema)
	Properties *PropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (String) ID of the Security Group this rule belongs to
	// ID of the Security Group this rule belongs to
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (List of String) List of tags for the Security Rule
	// List of tags for the Security Rule
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) ID of the VPC this Security Rule belongs to
	// ID of the VPC this Security Rule belongs to
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type SecurityRuleObservation struct {

	// (String) Security Rule identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Security Rule location
	// Security Rule location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Security Rule name
	// Security Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this Security Rule belongs to
	// ID of the project this Security Rule belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Properties of the security rule (see below for nested schema)
	Properties *PropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`

	// (String) ID of the Security Group this rule belongs to
	// ID of the Security Group this rule belongs to
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (List of String) List of tags for the Security Rule
	// List of tags for the Security Rule
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Security Rule URI
	// Security Rule URI
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) ID of the VPC this Security Rule belongs to
	// ID of the VPC this Security Rule belongs to
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type SecurityRuleParameters struct {

	// (String) Security Rule location
	// Security Rule location
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Security Rule name
	// Security Rule name
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this Security Rule belongs to
	// ID of the project this Security Rule belongs to
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Properties of the security rule (see below for nested schema)
	// +kubebuilder:validation:Required
	Properties *PropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (String) ID of the Security Group this rule belongs to
	// ID of the Security Group this rule belongs to
	// +kubebuilder:validation:Required
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (List of String) List of tags for the Security Rule
	// List of tags for the Security Rule
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) ID of the VPC this Security Rule belongs to
	// ID of the VPC this Security Rule belongs to
	// +kubebuilder:validation:Required
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type TargetInitParameters struct {

	// (String) Type of the target (Ip/SecurityGroup)
	// Type of the target (Ip/SecurityGroup)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Value of the target (CIDR or SecurityGroup URI)
	// Value of the target (CIDR or SecurityGroup URI)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TargetObservation struct {

	// (String) Type of the target (Ip/SecurityGroup)
	// Type of the target (Ip/SecurityGroup)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Value of the target (CIDR or SecurityGroup URI)
	// Value of the target (CIDR or SecurityGroup URI)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TargetParameters struct {

	// (String) Type of the target (Ip/SecurityGroup)
	// Type of the target (Ip/SecurityGroup)
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind" tf:"kind,omitempty"`

	// (String) Value of the target (CIDR or SecurityGroup URI)
	// Value of the target (CIDR or SecurityGroup URI)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// SecurityRuleSpec defines the desired state of SecurityRule
type SecurityRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SecurityRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityRuleInitParameters `json:"initProvider,omitempty"`
}

// SecurityRuleStatus defines the observed state of SecurityRule.
type SecurityRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecurityRule is the Schema for the SecurityRules API. Manages an ArubaCloud Security Rule.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,arubacloud}
type SecurityRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.properties) || (has(self.initProvider) && has(self.initProvider.properties))",message="spec.forProvider.properties is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.securityGroupId) || (has(self.initProvider) && has(self.initProvider.securityGroupId))",message="spec.forProvider.securityGroupId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcId) || (has(self.initProvider) && has(self.initProvider.vpcId))",message="spec.forProvider.vpcId is a required parameter"
	Spec   SecurityRuleSpec   `json:"spec"`
	Status SecurityRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityRuleList contains a list of SecurityRules
type SecurityRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityRule `json:"items"`
}

// Repository type metadata.
var (
	SecurityRule_Kind             = "SecurityRule"
	SecurityRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecurityRule_Kind}.String()
	SecurityRule_KindAPIVersion   = SecurityRule_Kind + "." + CRDGroupVersion.String()
	SecurityRule_GroupVersionKind = CRDGroupVersion.WithKind(SecurityRule_Kind)
)

func init() {
	SchemeBuilder.Register(&SecurityRule{}, &SecurityRuleList{})
}
