// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RestoreInitParameters struct {

	// (String) ID of the backup to restore from.
	// ID of the backup to restore from.
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the restore operation.
	// Display name for the restore operation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) ID of the target block storage volume to restore the backup onto.
	// ID of the target block storage volume to restore the backup onto.
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

type RestoreObservation struct {

	// (String) ID of the backup to restore from.
	// ID of the backup to restore from.
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the restore operation.
	// Display name for the restore operation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) ID of the target block storage volume to restore the backup onto.
	// ID of the target block storage volume to restore the backup onto.
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

type RestoreParameters struct {

	// (String) ID of the backup to restore from.
	// ID of the backup to restore from.
	// +kubebuilder:validation:Required
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the restore operation.
	// Display name for the restore operation.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) ID of the target block storage volume to restore the backup onto.
	// ID of the target block storage volume to restore the backup onto.
	// +kubebuilder:validation:Required
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

// RestoreSpec defines the desired state of Restore
type RestoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RestoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RestoreInitParameters `json:"initProvider,omitempty"`
}

// RestoreStatus defines the observed state of Restore.
type RestoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RestoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Restore is the Schema for the Restores API. Manages an ArubaCloud Block Storage Restore operation — restores a backup to a block storage volume.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,arubacloud}
type Restore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.backupId) || (has(self.initProvider) && has(self.initProvider.backupId))",message="spec.forProvider.backupId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.volumeId) || (has(self.initProvider) && has(self.initProvider.volumeId))",message="spec.forProvider.volumeId is a required parameter"
	Spec   RestoreSpec   `json:"spec"`
	Status RestoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RestoreList contains a list of Restores
type RestoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Restore `json:"items"`
}

// Repository type metadata.
var (
	Restore_Kind             = "Restore"
	Restore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Restore_Kind}.String()
	Restore_KindAPIVersion   = Restore_Kind + "." + CRDGroupVersion.String()
	Restore_GroupVersionKind = CRDGroupVersion.WithKind(Restore_Kind)
)

func init() {
	SchemeBuilder.Register(&Restore{}, &RestoreList{})
}
