//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EspInitParameters) DeepCopyInto(out *EspInitParameters) {
	*out = *in
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(float64)
		**out = **in
	}
	if in.Pfs != nil {
		in, out := &in.Pfs, &out.Pfs
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EspInitParameters.
func (in *EspInitParameters) DeepCopy() *EspInitParameters {
	if in == nil {
		return nil
	}
	out := new(EspInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EspObservation) DeepCopyInto(out *EspObservation) {
	*out = *in
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(float64)
		**out = **in
	}
	if in.Pfs != nil {
		in, out := &in.Pfs, &out.Pfs
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EspObservation.
func (in *EspObservation) DeepCopy() *EspObservation {
	if in == nil {
		return nil
	}
	out := new(EspObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EspParameters) DeepCopyInto(out *EspParameters) {
	*out = *in
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(float64)
		**out = **in
	}
	if in.Pfs != nil {
		in, out := &in.Pfs, &out.Pfs
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EspParameters.
func (in *EspParameters) DeepCopy() *EspParameters {
	if in == nil {
		return nil
	}
	out := new(EspParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigurationsInitParameters) DeepCopyInto(out *IPConfigurationsInitParameters) {
	*out = *in
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(PublicIPInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(SubnetInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPC != nil {
		in, out := &in.VPC, &out.VPC
		*out = new(VPCInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigurationsInitParameters.
func (in *IPConfigurationsInitParameters) DeepCopy() *IPConfigurationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(IPConfigurationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigurationsObservation) DeepCopyInto(out *IPConfigurationsObservation) {
	*out = *in
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(PublicIPObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(SubnetObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.VPC != nil {
		in, out := &in.VPC, &out.VPC
		*out = new(VPCObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigurationsObservation.
func (in *IPConfigurationsObservation) DeepCopy() *IPConfigurationsObservation {
	if in == nil {
		return nil
	}
	out := new(IPConfigurationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigurationsParameters) DeepCopyInto(out *IPConfigurationsParameters) {
	*out = *in
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(PublicIPParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(SubnetParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPC != nil {
		in, out := &in.VPC, &out.VPC
		*out = new(VPCParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigurationsParameters.
func (in *IPConfigurationsParameters) DeepCopy() *IPConfigurationsParameters {
	if in == nil {
		return nil
	}
	out := new(IPConfigurationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IkeInitParameters) DeepCopyInto(out *IkeInitParameters) {
	*out = *in
	if in.DhGroup != nil {
		in, out := &in.DhGroup, &out.DhGroup
		*out = new(string)
		**out = **in
	}
	if in.DpdAction != nil {
		in, out := &in.DpdAction, &out.DpdAction
		*out = new(string)
		**out = **in
	}
	if in.DpdInterval != nil {
		in, out := &in.DpdInterval, &out.DpdInterval
		*out = new(float64)
		**out = **in
	}
	if in.DpdTimeout != nil {
		in, out := &in.DpdTimeout, &out.DpdTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IkeInitParameters.
func (in *IkeInitParameters) DeepCopy() *IkeInitParameters {
	if in == nil {
		return nil
	}
	out := new(IkeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IkeObservation) DeepCopyInto(out *IkeObservation) {
	*out = *in
	if in.DhGroup != nil {
		in, out := &in.DhGroup, &out.DhGroup
		*out = new(string)
		**out = **in
	}
	if in.DpdAction != nil {
		in, out := &in.DpdAction, &out.DpdAction
		*out = new(string)
		**out = **in
	}
	if in.DpdInterval != nil {
		in, out := &in.DpdInterval, &out.DpdInterval
		*out = new(float64)
		**out = **in
	}
	if in.DpdTimeout != nil {
		in, out := &in.DpdTimeout, &out.DpdTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IkeObservation.
func (in *IkeObservation) DeepCopy() *IkeObservation {
	if in == nil {
		return nil
	}
	out := new(IkeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IkeParameters) DeepCopyInto(out *IkeParameters) {
	*out = *in
	if in.DhGroup != nil {
		in, out := &in.DhGroup, &out.DhGroup
		*out = new(string)
		**out = **in
	}
	if in.DpdAction != nil {
		in, out := &in.DpdAction, &out.DpdAction
		*out = new(string)
		**out = **in
	}
	if in.DpdInterval != nil {
		in, out := &in.DpdInterval, &out.DpdInterval
		*out = new(float64)
		**out = **in
	}
	if in.DpdTimeout != nil {
		in, out := &in.DpdTimeout, &out.DpdTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IkeParameters.
func (in *IkeParameters) DeepCopy() *IkeParameters {
	if in == nil {
		return nil
	}
	out := new(IkeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertiesInitParameters) DeepCopyInto(out *PropertiesInitParameters) {
	*out = *in
	if in.BillingPeriod != nil {
		in, out := &in.BillingPeriod, &out.BillingPeriod
		*out = new(string)
		**out = **in
	}
	if in.IPConfigurations != nil {
		in, out := &in.IPConfigurations, &out.IPConfigurations
		*out = new(IPConfigurationsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPNClientProtocol != nil {
		in, out := &in.VPNClientProtocol, &out.VPNClientProtocol
		*out = new(string)
		**out = **in
	}
	if in.VPNClientSettings != nil {
		in, out := &in.VPNClientSettings, &out.VPNClientSettings
		*out = new(VPNClientSettingsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPNType != nil {
		in, out := &in.VPNType, &out.VPNType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertiesInitParameters.
func (in *PropertiesInitParameters) DeepCopy() *PropertiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(PropertiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertiesObservation) DeepCopyInto(out *PropertiesObservation) {
	*out = *in
	if in.BillingPeriod != nil {
		in, out := &in.BillingPeriod, &out.BillingPeriod
		*out = new(string)
		**out = **in
	}
	if in.IPConfigurations != nil {
		in, out := &in.IPConfigurations, &out.IPConfigurations
		*out = new(IPConfigurationsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.VPNClientProtocol != nil {
		in, out := &in.VPNClientProtocol, &out.VPNClientProtocol
		*out = new(string)
		**out = **in
	}
	if in.VPNClientSettings != nil {
		in, out := &in.VPNClientSettings, &out.VPNClientSettings
		*out = new(VPNClientSettingsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.VPNType != nil {
		in, out := &in.VPNType, &out.VPNType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertiesObservation.
func (in *PropertiesObservation) DeepCopy() *PropertiesObservation {
	if in == nil {
		return nil
	}
	out := new(PropertiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertiesParameters) DeepCopyInto(out *PropertiesParameters) {
	*out = *in
	if in.BillingPeriod != nil {
		in, out := &in.BillingPeriod, &out.BillingPeriod
		*out = new(string)
		**out = **in
	}
	if in.IPConfigurations != nil {
		in, out := &in.IPConfigurations, &out.IPConfigurations
		*out = new(IPConfigurationsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPNClientProtocol != nil {
		in, out := &in.VPNClientProtocol, &out.VPNClientProtocol
		*out = new(string)
		**out = **in
	}
	if in.VPNClientSettings != nil {
		in, out := &in.VPNClientSettings, &out.VPNClientSettings
		*out = new(VPNClientSettingsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPNType != nil {
		in, out := &in.VPNType, &out.VPNType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertiesParameters.
func (in *PropertiesParameters) DeepCopy() *PropertiesParameters {
	if in == nil {
		return nil
	}
	out := new(PropertiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PskInitParameters) DeepCopyInto(out *PskInitParameters) {
	*out = *in
	if in.CloudSite != nil {
		in, out := &in.CloudSite, &out.CloudSite
		*out = new(string)
		**out = **in
	}
	if in.OnPremSite != nil {
		in, out := &in.OnPremSite, &out.OnPremSite
		*out = new(string)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PskInitParameters.
func (in *PskInitParameters) DeepCopy() *PskInitParameters {
	if in == nil {
		return nil
	}
	out := new(PskInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PskObservation) DeepCopyInto(out *PskObservation) {
	*out = *in
	if in.CloudSite != nil {
		in, out := &in.CloudSite, &out.CloudSite
		*out = new(string)
		**out = **in
	}
	if in.OnPremSite != nil {
		in, out := &in.OnPremSite, &out.OnPremSite
		*out = new(string)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PskObservation.
func (in *PskObservation) DeepCopy() *PskObservation {
	if in == nil {
		return nil
	}
	out := new(PskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PskParameters) DeepCopyInto(out *PskParameters) {
	*out = *in
	if in.CloudSite != nil {
		in, out := &in.CloudSite, &out.CloudSite
		*out = new(string)
		**out = **in
	}
	if in.OnPremSite != nil {
		in, out := &in.OnPremSite, &out.OnPremSite
		*out = new(string)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PskParameters.
func (in *PskParameters) DeepCopy() *PskParameters {
	if in == nil {
		return nil
	}
	out := new(PskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicIPInitParameters) DeepCopyInto(out *PublicIPInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicIPInitParameters.
func (in *PublicIPInitParameters) DeepCopy() *PublicIPInitParameters {
	if in == nil {
		return nil
	}
	out := new(PublicIPInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicIPObservation) DeepCopyInto(out *PublicIPObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicIPObservation.
func (in *PublicIPObservation) DeepCopy() *PublicIPObservation {
	if in == nil {
		return nil
	}
	out := new(PublicIPObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicIPParameters) DeepCopyInto(out *PublicIPParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicIPParameters.
func (in *PublicIPParameters) DeepCopy() *PublicIPParameters {
	if in == nil {
		return nil
	}
	out := new(PublicIPParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetInitParameters) DeepCopyInto(out *SubnetInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetInitParameters.
func (in *SubnetInitParameters) DeepCopy() *SubnetInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubnetInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetObservation) DeepCopyInto(out *SubnetObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetObservation.
func (in *SubnetObservation) DeepCopy() *SubnetObservation {
	if in == nil {
		return nil
	}
	out := new(SubnetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetParameters) DeepCopyInto(out *SubnetParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetParameters.
func (in *SubnetParameters) DeepCopy() *SubnetParameters {
	if in == nil {
		return nil
	}
	out := new(SubnetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInitParameters) DeepCopyInto(out *VPCInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInitParameters.
func (in *VPCInitParameters) DeepCopy() *VPCInitParameters {
	if in == nil {
		return nil
	}
	out := new(VPCInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCObservation) DeepCopyInto(out *VPCObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCObservation.
func (in *VPCObservation) DeepCopy() *VPCObservation {
	if in == nil {
		return nil
	}
	out := new(VPCObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCParameters) DeepCopyInto(out *VPCParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCParameters.
func (in *VPCParameters) DeepCopy() *VPCParameters {
	if in == nil {
		return nil
	}
	out := new(VPCParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientSettingsInitParameters) DeepCopyInto(out *VPNClientSettingsInitParameters) {
	*out = *in
	if in.Esp != nil {
		in, out := &in.Esp, &out.Esp
		*out = new(EspInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Ike != nil {
		in, out := &in.Ike, &out.Ike
		*out = new(IkeInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PeerClientPublicIP != nil {
		in, out := &in.PeerClientPublicIP, &out.PeerClientPublicIP
		*out = new(string)
		**out = **in
	}
	if in.Psk != nil {
		in, out := &in.Psk, &out.Psk
		*out = new(PskInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientSettingsInitParameters.
func (in *VPNClientSettingsInitParameters) DeepCopy() *VPNClientSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(VPNClientSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientSettingsObservation) DeepCopyInto(out *VPNClientSettingsObservation) {
	*out = *in
	if in.Esp != nil {
		in, out := &in.Esp, &out.Esp
		*out = new(EspObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Ike != nil {
		in, out := &in.Ike, &out.Ike
		*out = new(IkeObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.PeerClientPublicIP != nil {
		in, out := &in.PeerClientPublicIP, &out.PeerClientPublicIP
		*out = new(string)
		**out = **in
	}
	if in.Psk != nil {
		in, out := &in.Psk, &out.Psk
		*out = new(PskObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientSettingsObservation.
func (in *VPNClientSettingsObservation) DeepCopy() *VPNClientSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(VPNClientSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientSettingsParameters) DeepCopyInto(out *VPNClientSettingsParameters) {
	*out = *in
	if in.Esp != nil {
		in, out := &in.Esp, &out.Esp
		*out = new(EspParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Ike != nil {
		in, out := &in.Ike, &out.Ike
		*out = new(IkeParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PeerClientPublicIP != nil {
		in, out := &in.PeerClientPublicIP, &out.PeerClientPublicIP
		*out = new(string)
		**out = **in
	}
	if in.Psk != nil {
		in, out := &in.Psk, &out.Psk
		*out = new(PskParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientSettingsParameters.
func (in *VPNClientSettingsParameters) DeepCopy() *VPNClientSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(VPNClientSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vpntunnel) DeepCopyInto(out *Vpntunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vpntunnel.
func (in *Vpntunnel) DeepCopy() *Vpntunnel {
	if in == nil {
		return nil
	}
	out := new(Vpntunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vpntunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpntunnelInitParameters) DeepCopyInto(out *VpntunnelInitParameters) {
	*out = *in
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(PropertiesInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpntunnelInitParameters.
func (in *VpntunnelInitParameters) DeepCopy() *VpntunnelInitParameters {
	if in == nil {
		return nil
	}
	out := new(VpntunnelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpntunnelList) DeepCopyInto(out *VpntunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vpntunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpntunnelList.
func (in *VpntunnelList) DeepCopy() *VpntunnelList {
	if in == nil {
		return nil
	}
	out := new(VpntunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpntunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpntunnelObservation) DeepCopyInto(out *VpntunnelObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(PropertiesObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpntunnelObservation.
func (in *VpntunnelObservation) DeepCopy() *VpntunnelObservation {
	if in == nil {
		return nil
	}
	out := new(VpntunnelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpntunnelParameters) DeepCopyInto(out *VpntunnelParameters) {
	*out = *in
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(PropertiesParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpntunnelParameters.
func (in *VpntunnelParameters) DeepCopy() *VpntunnelParameters {
	if in == nil {
		return nil
	}
	out := new(VpntunnelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpntunnelSpec) DeepCopyInto(out *VpntunnelSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpntunnelSpec.
func (in *VpntunnelSpec) DeepCopy() *VpntunnelSpec {
	if in == nil {
		return nil
	}
	out := new(VpntunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpntunnelStatus) DeepCopyInto(out *VpntunnelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpntunnelStatus.
func (in *VpntunnelStatus) DeepCopy() *VpntunnelStatus {
	if in == nil {
		return nil
	}
	out := new(VpntunnelStatus)
	in.DeepCopyInto(out)
	return out
}
