// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type EspInitParameters struct {

	// (String) ESP encryption algorithm (e.g., aes256).
	// ESP encryption algorithm (e.g., `aes256`).
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) ESP integrity/hash algorithm (e.g., sha256).
	// ESP integrity/hash algorithm (e.g., `sha256`).
	Hash *string `json:"hash,omitempty" tf:"hash,omitempty"`

	// 2 lifetime in seconds.
	// ESP phase-2 lifetime in seconds.
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`

	// group<N>" (e.g. "dh-group14" for MODP-2048).
	// ESP Perfect Forward Secrecy group. Use `"enable"`, `"disable"`, or `"dh-group<N>"` (e.g. `"dh-group14"` for MODP-2048).
	Pfs *string `json:"pfs,omitempty" tf:"pfs,omitempty"`
}

type EspObservation struct {

	// (String) ESP encryption algorithm (e.g., aes256).
	// ESP encryption algorithm (e.g., `aes256`).
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) ESP integrity/hash algorithm (e.g., sha256).
	// ESP integrity/hash algorithm (e.g., `sha256`).
	Hash *string `json:"hash,omitempty" tf:"hash,omitempty"`

	// 2 lifetime in seconds.
	// ESP phase-2 lifetime in seconds.
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`

	// group<N>" (e.g. "dh-group14" for MODP-2048).
	// ESP Perfect Forward Secrecy group. Use `"enable"`, `"disable"`, or `"dh-group<N>"` (e.g. `"dh-group14"` for MODP-2048).
	Pfs *string `json:"pfs,omitempty" tf:"pfs,omitempty"`
}

type EspParameters struct {

	// (String) ESP encryption algorithm (e.g., aes256).
	// ESP encryption algorithm (e.g., `aes256`).
	// +kubebuilder:validation:Optional
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) ESP integrity/hash algorithm (e.g., sha256).
	// ESP integrity/hash algorithm (e.g., `sha256`).
	// +kubebuilder:validation:Optional
	Hash *string `json:"hash,omitempty" tf:"hash,omitempty"`

	// 2 lifetime in seconds.
	// ESP phase-2 lifetime in seconds.
	// +kubebuilder:validation:Optional
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`

	// group<N>" (e.g. "dh-group14" for MODP-2048).
	// ESP Perfect Forward Secrecy group. Use `"enable"`, `"disable"`, or `"dh-group<N>"` (e.g. `"dh-group14"` for MODP-2048).
	// +kubebuilder:validation:Optional
	Pfs *string `json:"pfs,omitempty" tf:"pfs,omitempty"`
}

type IPConfigurationsInitParameters struct {

	// (Attributes) Reference to the elastic public IP assigned to this tunnel. (see below for nested schema)
	PublicIP *PublicIPInitParameters `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// (Attributes) Reference to the subnet used by this tunnel. (see below for nested schema)
	Subnet *SubnetInitParameters `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// (Attributes) Reference to the VPC this tunnel is attached to. (see below for nested schema)
	VPC *VPCInitParameters `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type IPConfigurationsObservation struct {

	// (Attributes) Reference to the elastic public IP assigned to this tunnel. (see below for nested schema)
	PublicIP *PublicIPObservation `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// (Attributes) Reference to the subnet used by this tunnel. (see below for nested schema)
	Subnet *SubnetObservation `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// (Attributes) Reference to the VPC this tunnel is attached to. (see below for nested schema)
	VPC *VPCObservation `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type IPConfigurationsParameters struct {

	// (Attributes) Reference to the elastic public IP assigned to this tunnel. (see below for nested schema)
	// +kubebuilder:validation:Optional
	PublicIP *PublicIPParameters `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// (Attributes) Reference to the subnet used by this tunnel. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Subnet *SubnetParameters `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// (Attributes) Reference to the VPC this tunnel is attached to. (see below for nested schema)
	// +kubebuilder:validation:Optional
	VPC *VPCParameters `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type IkeInitParameters struct {

	// Hellman group. Use the numeric group identifier: "1", "2", "5", "14" … "32". The common choice for IKEv2 is "14" (MODP-2048).
	// IKE Diffie-Hellman group. Use the numeric group identifier: `"1"`, `"2"`, `"5"`, `"14"` … `"32"`. The common choice for IKEv2 is `"14"` (MODP-2048).
	DhGroup *string `json:"dhGroup,omitempty" tf:"dh_group,omitempty"`

	// (String) Dead Peer Detection action on failure (e.g., restart).
	// Dead Peer Detection action on failure (e.g., `restart`).
	DpdAction *string `json:"dpdAction,omitempty" tf:"dpd_action,omitempty"`

	// alive interval in seconds.
	// DPD keep-alive interval in seconds.
	DpdInterval *float64 `json:"dpdInterval,omitempty" tf:"dpd_interval,omitempty"`

	// (Number) DPD timeout before the peer is considered dead, in seconds.
	// DPD timeout before the peer is considered dead, in seconds.
	DpdTimeout *float64 `json:"dpdTimeout,omitempty" tf:"dpd_timeout,omitempty"`

	// (String) ESP encryption algorithm (e.g., aes256).
	// IKE encryption algorithm (e.g., `aes256`).
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) ESP integrity/hash algorithm (e.g., sha256).
	// IKE integrity/hash algorithm (e.g., `sha256`).
	Hash *string `json:"hash,omitempty" tf:"hash,omitempty"`

	// 2 lifetime in seconds.
	// IKE phase-1 lifetime in seconds.
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`
}

type IkeObservation struct {

	// Hellman group. Use the numeric group identifier: "1", "2", "5", "14" … "32". The common choice for IKEv2 is "14" (MODP-2048).
	// IKE Diffie-Hellman group. Use the numeric group identifier: `"1"`, `"2"`, `"5"`, `"14"` … `"32"`. The common choice for IKEv2 is `"14"` (MODP-2048).
	DhGroup *string `json:"dhGroup,omitempty" tf:"dh_group,omitempty"`

	// (String) Dead Peer Detection action on failure (e.g., restart).
	// Dead Peer Detection action on failure (e.g., `restart`).
	DpdAction *string `json:"dpdAction,omitempty" tf:"dpd_action,omitempty"`

	// alive interval in seconds.
	// DPD keep-alive interval in seconds.
	DpdInterval *float64 `json:"dpdInterval,omitempty" tf:"dpd_interval,omitempty"`

	// (Number) DPD timeout before the peer is considered dead, in seconds.
	// DPD timeout before the peer is considered dead, in seconds.
	DpdTimeout *float64 `json:"dpdTimeout,omitempty" tf:"dpd_timeout,omitempty"`

	// (String) ESP encryption algorithm (e.g., aes256).
	// IKE encryption algorithm (e.g., `aes256`).
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) ESP integrity/hash algorithm (e.g., sha256).
	// IKE integrity/hash algorithm (e.g., `sha256`).
	Hash *string `json:"hash,omitempty" tf:"hash,omitempty"`

	// 2 lifetime in seconds.
	// IKE phase-1 lifetime in seconds.
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`
}

type IkeParameters struct {

	// Hellman group. Use the numeric group identifier: "1", "2", "5", "14" … "32". The common choice for IKEv2 is "14" (MODP-2048).
	// IKE Diffie-Hellman group. Use the numeric group identifier: `"1"`, `"2"`, `"5"`, `"14"` … `"32"`. The common choice for IKEv2 is `"14"` (MODP-2048).
	// +kubebuilder:validation:Optional
	DhGroup *string `json:"dhGroup,omitempty" tf:"dh_group,omitempty"`

	// (String) Dead Peer Detection action on failure (e.g., restart).
	// Dead Peer Detection action on failure (e.g., `restart`).
	// +kubebuilder:validation:Optional
	DpdAction *string `json:"dpdAction,omitempty" tf:"dpd_action,omitempty"`

	// alive interval in seconds.
	// DPD keep-alive interval in seconds.
	// +kubebuilder:validation:Optional
	DpdInterval *float64 `json:"dpdInterval,omitempty" tf:"dpd_interval,omitempty"`

	// (Number) DPD timeout before the peer is considered dead, in seconds.
	// DPD timeout before the peer is considered dead, in seconds.
	// +kubebuilder:validation:Optional
	DpdTimeout *float64 `json:"dpdTimeout,omitempty" tf:"dpd_timeout,omitempty"`

	// (String) ESP encryption algorithm (e.g., aes256).
	// IKE encryption algorithm (e.g., `aes256`).
	// +kubebuilder:validation:Optional
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) ESP integrity/hash algorithm (e.g., sha256).
	// IKE integrity/hash algorithm (e.g., `sha256`).
	// +kubebuilder:validation:Optional
	Hash *string `json:"hash,omitempty" tf:"hash,omitempty"`

	// 2 lifetime in seconds.
	// IKE phase-1 lifetime in seconds.
	// +kubebuilder:validation:Optional
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`
}

type PropertiesInitParameters struct {

	// (String) Billing cycle for the resource. Accepted values: Hour, Month, Year.
	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Attributes) Network references for the VPN tunnel — VPC, subnet, and public IP. (see below for nested schema)
	IPConfigurations *IPConfigurationsInitParameters `json:"ipConfigurations,omitempty" tf:"ip_configurations,omitempty"`

	// (String) IKE protocol version. Accepted values: ikev2.
	// IKE protocol version. Accepted values: `ikev2`.
	VPNClientProtocol *string `json:"vpnClientProtocol,omitempty" tf:"vpn_client_protocol,omitempty"`

	// (Attributes) IKE/ESP/PSK client settings for the VPN tunnel. (see below for nested schema)
	VPNClientSettings *VPNClientSettingsInitParameters `json:"vpnClientSettings,omitempty" tf:"vpn_client_settings,omitempty"`

	// To-Site.
	// Type of VPN tunnel. Accepted values: `Site-To-Site`.
	VPNType *string `json:"vpnType,omitempty" tf:"vpn_type,omitempty"`
}

type PropertiesObservation struct {

	// (String) Billing cycle for the resource. Accepted values: Hour, Month, Year.
	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Attributes) Network references for the VPN tunnel — VPC, subnet, and public IP. (see below for nested schema)
	IPConfigurations *IPConfigurationsObservation `json:"ipConfigurations,omitempty" tf:"ip_configurations,omitempty"`

	// (String) IKE protocol version. Accepted values: ikev2.
	// IKE protocol version. Accepted values: `ikev2`.
	VPNClientProtocol *string `json:"vpnClientProtocol,omitempty" tf:"vpn_client_protocol,omitempty"`

	// (Attributes) IKE/ESP/PSK client settings for the VPN tunnel. (see below for nested schema)
	VPNClientSettings *VPNClientSettingsObservation `json:"vpnClientSettings,omitempty" tf:"vpn_client_settings,omitempty"`

	// To-Site.
	// Type of VPN tunnel. Accepted values: `Site-To-Site`.
	VPNType *string `json:"vpnType,omitempty" tf:"vpn_type,omitempty"`
}

type PropertiesParameters struct {

	// (String) Billing cycle for the resource. Accepted values: Hour, Month, Year.
	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Attributes) Network references for the VPN tunnel — VPC, subnet, and public IP. (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPConfigurations *IPConfigurationsParameters `json:"ipConfigurations,omitempty" tf:"ip_configurations,omitempty"`

	// (String) IKE protocol version. Accepted values: ikev2.
	// IKE protocol version. Accepted values: `ikev2`.
	// +kubebuilder:validation:Optional
	VPNClientProtocol *string `json:"vpnClientProtocol,omitempty" tf:"vpn_client_protocol,omitempty"`

	// (Attributes) IKE/ESP/PSK client settings for the VPN tunnel. (see below for nested schema)
	// +kubebuilder:validation:Optional
	VPNClientSettings *VPNClientSettingsParameters `json:"vpnClientSettings,omitempty" tf:"vpn_client_settings,omitempty"`

	// To-Site.
	// Type of VPN tunnel. Accepted values: `Site-To-Site`.
	// +kubebuilder:validation:Optional
	VPNType *string `json:"vpnType,omitempty" tf:"vpn_type,omitempty"`
}

type PskInitParameters struct {

	// shared key for the ArubaCloud side of the tunnel.
	// Pre-shared key for the ArubaCloud side of the tunnel.
	CloudSite *string `json:"cloudSite,omitempty" tf:"cloud_site,omitempty"`

	// shared key for the on-premises side of the tunnel.
	// Pre-shared key for the on-premises side of the tunnel.
	OnPremSite *string `json:"onPremSite,omitempty" tf:"on_prem_site,omitempty"`

	// — sent to the API but not returned in read responses.
	// Shared secret used to authenticate the VPN tunnel. Write-only — this value is sent to the API but is not returned in subsequent read responses.
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`
}

type PskObservation struct {

	// shared key for the ArubaCloud side of the tunnel.
	// Pre-shared key for the ArubaCloud side of the tunnel.
	CloudSite *string `json:"cloudSite,omitempty" tf:"cloud_site,omitempty"`

	// shared key for the on-premises side of the tunnel.
	// Pre-shared key for the on-premises side of the tunnel.
	OnPremSite *string `json:"onPremSite,omitempty" tf:"on_prem_site,omitempty"`

	// — sent to the API but not returned in read responses.
	// Shared secret used to authenticate the VPN tunnel. Write-only — this value is sent to the API but is not returned in subsequent read responses.
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`
}

type PskParameters struct {

	// shared key for the ArubaCloud side of the tunnel.
	// Pre-shared key for the ArubaCloud side of the tunnel.
	// +kubebuilder:validation:Optional
	CloudSite *string `json:"cloudSite,omitempty" tf:"cloud_site,omitempty"`

	// shared key for the on-premises side of the tunnel.
	// Pre-shared key for the on-premises side of the tunnel.
	// +kubebuilder:validation:Optional
	OnPremSite *string `json:"onPremSite,omitempty" tf:"on_prem_site,omitempty"`

	// — sent to the API but not returned in read responses.
	// Shared secret used to authenticate the VPN tunnel. Write-only — this value is sent to the API but is not returned in subsequent read responses.
	// +kubebuilder:validation:Optional
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`
}

type PublicIPInitParameters struct {

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the elastic public IP.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PublicIPObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the elastic public IP.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PublicIPParameters struct {

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the elastic public IP.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SubnetInitParameters struct {

	// (String) CIDR block of the subnet (e.g. 192.168.10.0/24). Required by the API.
	// CIDR block of the subnet (e.g. `192.168.10.0/24`). Required by the API.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the subnet.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SubnetObservation struct {

	// (String) CIDR block of the subnet (e.g. 192.168.10.0/24). Required by the API.
	// CIDR block of the subnet (e.g. `192.168.10.0/24`). Required by the API.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the subnet.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SubnetParameters struct {

	// (String) CIDR block of the subnet (e.g. 192.168.10.0/24). Required by the API.
	// CIDR block of the subnet (e.g. `192.168.10.0/24`). Required by the API.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the subnet.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type VPCInitParameters struct {

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the VPC.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type VPCObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the VPC.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type VPCParameters struct {

	// (String) Computed by the API. Unique identifier for the resource.
	// ID of the VPC.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type VPNClientSettingsInitParameters struct {

	// 2 settings. (see below for nested schema)
	Esp *EspInitParameters `json:"esp,omitempty" tf:"esp,omitempty"`

	// 1 settings. (see below for nested schema)
	Ike *IkeInitParameters `json:"ike,omitempty" tf:"ike,omitempty"`

	// premises gateway).
	// Public IP address of the remote peer (on-premises gateway).
	PeerClientPublicIP *string `json:"peerClientPublicIp,omitempty" tf:"peer_client_public_ip,omitempty"`

	// Shared Key (PSK) authentication settings. (see below for nested schema)
	Psk *PskInitParameters `json:"psk,omitempty" tf:"psk,omitempty"`
}

type VPNClientSettingsObservation struct {

	// 2 settings. (see below for nested schema)
	Esp *EspObservation `json:"esp,omitempty" tf:"esp,omitempty"`

	// 1 settings. (see below for nested schema)
	Ike *IkeObservation `json:"ike,omitempty" tf:"ike,omitempty"`

	// premises gateway).
	// Public IP address of the remote peer (on-premises gateway).
	PeerClientPublicIP *string `json:"peerClientPublicIp,omitempty" tf:"peer_client_public_ip,omitempty"`

	// Shared Key (PSK) authentication settings. (see below for nested schema)
	Psk *PskObservation `json:"psk,omitempty" tf:"psk,omitempty"`
}

type VPNClientSettingsParameters struct {

	// 2 settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Esp *EspParameters `json:"esp,omitempty" tf:"esp,omitempty"`

	// 1 settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Ike *IkeParameters `json:"ike,omitempty" tf:"ike,omitempty"`

	// premises gateway).
	// Public IP address of the remote peer (on-premises gateway).
	// +kubebuilder:validation:Optional
	PeerClientPublicIP *string `json:"peerClientPublicIp,omitempty" tf:"peer_client_public_ip,omitempty"`

	// Shared Key (PSK) authentication settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Psk *PskParameters `json:"psk,omitempty" tf:"psk,omitempty"`
}

type VPNTunnelInitParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN tunnel.
	// Display name for the VPN tunnel.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Configuration properties for the VPN tunnel. (see below for nested schema)
	Properties *PropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type VPNTunnelObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN tunnel.
	// Display name for the VPN tunnel.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Configuration properties for the VPN tunnel. (see below for nested schema)
	Properties *PropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type VPNTunnelParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN tunnel.
	// Display name for the VPN tunnel.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Configuration properties for the VPN tunnel. (see below for nested schema)
	// +kubebuilder:validation:Required
	Properties *PropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// VPNTunnelSpec defines the desired state of VPNTunnel
type VPNTunnelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VPNTunnelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPNTunnelInitParameters `json:"initProvider,omitempty"`
}

// VPNTunnelStatus defines the observed state of VPNTunnel.
type VPNTunnelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VPNTunnelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPNTunnel is the Schema for the VPNTunnels API. Manages an ArubaCloud VPN Tunnel — an IPSec site-to-site VPN connection between an ArubaCloud VPC and an external network.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type VPNTunnel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.properties) || (has(self.initProvider) && has(self.initProvider.properties))",message="spec.forProvider.properties is a required parameter"
	Spec   VPNTunnelSpec   `json:"spec"`
	Status VPNTunnelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPNTunnelList contains a list of VPNTunnels
type VPNTunnelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPNTunnel `json:"items"`
}

// Repository type metadata.
var (
	VPNTunnel_Kind             = "VPNTunnel"
	VPNTunnel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPNTunnel_Kind}.String()
	VPNTunnel_KindAPIVersion   = VPNTunnel_Kind + "." + CRDGroupVersion.String()
	VPNTunnel_GroupVersionKind = CRDGroupVersion.WithKind(VPNTunnel_Kind)
)

func init() {
	SchemeBuilder.Register(&VPNTunnel{}, &VPNTunnelList{})
}
