apiVersion: restore.arubacloud.m.crossplane.io/v1alpha1
kind: Restore
metadata:
  annotations:
    meta.upbound.io/example-id: restore/v1alpha1/restore
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    name: basic-restore
