//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRoute) DeepCopyInto(out *VPCPeeringRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRoute.
func (in *VPCPeeringRoute) DeepCopy() *VPCPeeringRoute {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCPeeringRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRouteInitParameters) DeepCopyInto(out *VPCPeeringRouteInitParameters) {
	*out = *in
	if in.BillingPeriod != nil {
		in, out := &in.BillingPeriod, &out.BillingPeriod
		*out = new(string)
		**out = **in
	}
	if in.LocalNetworkAddress != nil {
		in, out := &in.LocalNetworkAddress, &out.LocalNetworkAddress
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RemoteNetworkAddress != nil {
		in, out := &in.RemoteNetworkAddress, &out.RemoteNetworkAddress
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCPeeringID != nil {
		in, out := &in.VPCPeeringID, &out.VPCPeeringID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRouteInitParameters.
func (in *VPCPeeringRouteInitParameters) DeepCopy() *VPCPeeringRouteInitParameters {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRouteInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRouteList) DeepCopyInto(out *VPCPeeringRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCPeeringRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRouteList.
func (in *VPCPeeringRouteList) DeepCopy() *VPCPeeringRouteList {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCPeeringRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRouteObservation) DeepCopyInto(out *VPCPeeringRouteObservation) {
	*out = *in
	if in.BillingPeriod != nil {
		in, out := &in.BillingPeriod, &out.BillingPeriod
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LocalNetworkAddress != nil {
		in, out := &in.LocalNetworkAddress, &out.LocalNetworkAddress
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RemoteNetworkAddress != nil {
		in, out := &in.RemoteNetworkAddress, &out.RemoteNetworkAddress
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCPeeringID != nil {
		in, out := &in.VPCPeeringID, &out.VPCPeeringID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRouteObservation.
func (in *VPCPeeringRouteObservation) DeepCopy() *VPCPeeringRouteObservation {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRouteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRouteParameters) DeepCopyInto(out *VPCPeeringRouteParameters) {
	*out = *in
	if in.BillingPeriod != nil {
		in, out := &in.BillingPeriod, &out.BillingPeriod
		*out = new(string)
		**out = **in
	}
	if in.LocalNetworkAddress != nil {
		in, out := &in.LocalNetworkAddress, &out.LocalNetworkAddress
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RemoteNetworkAddress != nil {
		in, out := &in.RemoteNetworkAddress, &out.RemoteNetworkAddress
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCPeeringID != nil {
		in, out := &in.VPCPeeringID, &out.VPCPeeringID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRouteParameters.
func (in *VPCPeeringRouteParameters) DeepCopy() *VPCPeeringRouteParameters {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRouteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRouteSpec) DeepCopyInto(out *VPCPeeringRouteSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRouteSpec.
func (in *VPCPeeringRouteSpec) DeepCopy() *VPCPeeringRouteSpec {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeeringRouteStatus) DeepCopyInto(out *VPCPeeringRouteStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeeringRouteStatus.
func (in *VPCPeeringRouteStatus) DeepCopy() *VPCPeeringRouteStatus {
	if in == nil {
		return nil
	}
	out := new(VPCPeeringRouteStatus)
	in.DeepCopyInto(out)
	return out
}
