// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type VPCPeeringRouteInitParameters struct {

	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Local network CIDR that is reachable on this side of the peering (e.g., `10.0.1.0/24`).
	LocalNetworkAddress *string `json:"localNetworkAddress,omitempty" tf:"local_network_address,omitempty"`

	// Display name for the VPC peering route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Remote network CIDR reachable through the peering connection (e.g., `10.0.2.0/24`).
	RemoteNetworkAddress *string `json:"remoteNetworkAddress,omitempty" tf:"remote_network_address,omitempty"`

	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// ID of the VPC this peering route belongs to.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// ID of the VPC peering connection this route belongs to.
	VPCPeeringID *string `json:"vpcPeeringId,omitempty" tf:"vpc_peering_id,omitempty"`
}

type VPCPeeringRouteObservation struct {

	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Local network CIDR that is reachable on this side of the peering (e.g., `10.0.1.0/24`).
	LocalNetworkAddress *string `json:"localNetworkAddress,omitempty" tf:"local_network_address,omitempty"`

	// Display name for the VPC peering route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Remote network CIDR reachable through the peering connection (e.g., `10.0.2.0/24`).
	RemoteNetworkAddress *string `json:"remoteNetworkAddress,omitempty" tf:"remote_network_address,omitempty"`

	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// ID of the VPC this peering route belongs to.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// ID of the VPC peering connection this route belongs to.
	VPCPeeringID *string `json:"vpcPeeringId,omitempty" tf:"vpc_peering_id,omitempty"`
}

type VPCPeeringRouteParameters struct {

	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Required
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Local network CIDR that is reachable on this side of the peering (e.g., `10.0.1.0/24`).
	// +kubebuilder:validation:Required
	LocalNetworkAddress *string `json:"localNetworkAddress,omitempty" tf:"local_network_address,omitempty"`

	// Display name for the VPC peering route.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the project that owns this resource.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Remote network CIDR reachable through the peering connection (e.g., `10.0.2.0/24`).
	// +kubebuilder:validation:Required
	RemoteNetworkAddress *string `json:"remoteNetworkAddress,omitempty" tf:"remote_network_address,omitempty"`

	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// ID of the VPC this peering route belongs to.
	// +kubebuilder:validation:Required
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// ID of the VPC peering connection this route belongs to.
	// +kubebuilder:validation:Required
	VPCPeeringID *string `json:"vpcPeeringId,omitempty" tf:"vpc_peering_id,omitempty"`
}

// VPCPeeringRouteSpec defines the desired state of VPCPeeringRoute
type VPCPeeringRouteSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VPCPeeringRouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPCPeeringRouteInitParameters `json:"initProvider,omitempty"`
}

// VPCPeeringRouteStatus defines the observed state of VPCPeeringRoute.
type VPCPeeringRouteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VPCPeeringRouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPCPeeringRoute is the Schema for the VPCPeeringRoutes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type VPCPeeringRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.localNetworkAddress) || (has(self.initProvider) && has(self.initProvider.localNetworkAddress))",message="spec.forProvider.localNetworkAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.remoteNetworkAddress) || (has(self.initProvider) && has(self.initProvider.remoteNetworkAddress))",message="spec.forProvider.remoteNetworkAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcId) || (has(self.initProvider) && has(self.initProvider.vpcId))",message="spec.forProvider.vpcId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcPeeringId) || (has(self.initProvider) && has(self.initProvider.vpcPeeringId))",message="spec.forProvider.vpcPeeringId is a required parameter"
	Spec   VPCPeeringRouteSpec   `json:"spec"`
	Status VPCPeeringRouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPCPeeringRouteList contains a list of VPCPeeringRoutes
type VPCPeeringRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCPeeringRoute `json:"items"`
}

// Repository type metadata.
var (
	VPCPeeringRoute_Kind             = "VPCPeeringRoute"
	VPCPeeringRoute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPCPeeringRoute_Kind}.String()
	VPCPeeringRoute_KindAPIVersion   = VPCPeeringRoute_Kind + "." + CRDGroupVersion.String()
	VPCPeeringRoute_GroupVersionKind = CRDGroupVersion.WithKind(VPCPeeringRoute_Kind)
)

func init() {
	SchemeBuilder.Register(&VPCPeeringRoute{}, &VPCPeeringRouteList{})
}
