// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PropertiesInitParameters struct {

	// side subnet to route over this tunnel (e.g., 10.0.1.0/24).
	// CIDR of the ArubaCloud-side subnet to route over this tunnel (e.g., `10.0.1.0/24`).
	CloudSubnet *string `json:"cloudSubnet,omitempty" tf:"cloud_subnet,omitempty"`

	// premises subnet reachable through this tunnel (e.g., 192.168.1.0/24).
	// CIDR of the on-premises subnet reachable through this tunnel (e.g., `192.168.1.0/24`).
	OnPremSubnet *string `json:"onPremSubnet,omitempty" tf:"on_prem_subnet,omitempty"`
}

type PropertiesObservation struct {

	// side subnet to route over this tunnel (e.g., 10.0.1.0/24).
	// CIDR of the ArubaCloud-side subnet to route over this tunnel (e.g., `10.0.1.0/24`).
	CloudSubnet *string `json:"cloudSubnet,omitempty" tf:"cloud_subnet,omitempty"`

	// premises subnet reachable through this tunnel (e.g., 192.168.1.0/24).
	// CIDR of the on-premises subnet reachable through this tunnel (e.g., `192.168.1.0/24`).
	OnPremSubnet *string `json:"onPremSubnet,omitempty" tf:"on_prem_subnet,omitempty"`
}

type PropertiesParameters struct {

	// side subnet to route over this tunnel (e.g., 10.0.1.0/24).
	// CIDR of the ArubaCloud-side subnet to route over this tunnel (e.g., `10.0.1.0/24`).
	// +kubebuilder:validation:Optional
	CloudSubnet *string `json:"cloudSubnet" tf:"cloud_subnet,omitempty"`

	// premises subnet reachable through this tunnel (e.g., 192.168.1.0/24).
	// CIDR of the on-premises subnet reachable through this tunnel (e.g., `192.168.1.0/24`).
	// +kubebuilder:validation:Optional
	OnPremSubnet *string `json:"onPremSubnet" tf:"on_prem_subnet,omitempty"`
}

type VPNRouteInitParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN route.
	// Display name for the VPN route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Routing properties for the VPN route. (see below for nested schema)
	Properties *PropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) ID of the VPN tunnel this route is associated with.
	// ID of the VPN tunnel this route is associated with.
	VPNTunnelID *string `json:"vpnTunnelId,omitempty" tf:"vpn_tunnel_id,omitempty"`
}

type VPNRouteObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN route.
	// Display name for the VPN route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Routing properties for the VPN route. (see below for nested schema)
	Properties *PropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) ID of the VPN tunnel this route is associated with.
	// ID of the VPN tunnel this route is associated with.
	VPNTunnelID *string `json:"vpnTunnelId,omitempty" tf:"vpn_tunnel_id,omitempty"`
}

type VPNRouteParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN route.
	// Display name for the VPN route.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Routing properties for the VPN route. (see below for nested schema)
	// +kubebuilder:validation:Required
	Properties *PropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) ID of the VPN tunnel this route is associated with.
	// ID of the VPN tunnel this route is associated with.
	// +kubebuilder:validation:Required
	VPNTunnelID *string `json:"vpnTunnelId,omitempty" tf:"vpn_tunnel_id,omitempty"`
}

// VPNRouteSpec defines the desired state of VPNRoute
type VPNRouteSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VPNRouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPNRouteInitParameters `json:"initProvider,omitempty"`
}

// VPNRouteStatus defines the observed state of VPNRoute.
type VPNRouteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VPNRouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPNRoute is the Schema for the VPNRoutes API. Manages a static route associated with an ArubaCloud VPN Tunnel.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type VPNRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.properties) || (has(self.initProvider) && has(self.initProvider.properties))",message="spec.forProvider.properties is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpnTunnelId) || (has(self.initProvider) && has(self.initProvider.vpnTunnelId))",message="spec.forProvider.vpnTunnelId is a required parameter"
	Spec   VPNRouteSpec   `json:"spec"`
	Status VPNRouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPNRouteList contains a list of VPNRoutes
type VPNRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPNRoute `json:"items"`
}

// Repository type metadata.
var (
	VPNRoute_Kind             = "VPNRoute"
	VPNRoute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPNRoute_Kind}.String()
	VPNRoute_KindAPIVersion   = VPNRoute_Kind + "." + CRDGroupVersion.String()
	VPNRoute_GroupVersionKind = CRDGroupVersion.WithKind(VPNRoute_Kind)
)

func init() {
	SchemeBuilder.Register(&VPNRoute{}, &VPNRouteList{})
}
