// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DatabasebackupInitParameters struct {

	// (String) Billing period
	// Billing period
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Database name to backup
	// Database name to backup
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) DBaaS ID this backup belongs to
	// DBaaS ID this backup belongs to
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (String) Database Backup location
	// Database Backup location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Database Backup name
	// Database Backup name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this backup belongs to
	// ID of the project this backup belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of tags for the Database Backup resource
	// List of tags for the Database Backup resource
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Zone for the Database Backup
	// Zone for the Database Backup
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DatabasebackupObservation struct {

	// (String) Billing period
	// Billing period
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Database name to backup
	// Database name to backup
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) DBaaS ID this backup belongs to
	// DBaaS ID this backup belongs to
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (String) Database Backup identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Database Backup location
	// Database Backup location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Database Backup name
	// Database Backup name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this backup belongs to
	// ID of the project this backup belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of tags for the Database Backup resource
	// List of tags for the Database Backup resource
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Database Backup URI
	// Database Backup URI
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) Zone for the Database Backup
	// Zone for the Database Backup
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DatabasebackupParameters struct {

	// (String) Billing period
	// Billing period
	// +kubebuilder:validation:Required
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Database name to backup
	// Database name to backup
	// +kubebuilder:validation:Required
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) DBaaS ID this backup belongs to
	// DBaaS ID this backup belongs to
	// +kubebuilder:validation:Required
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (String) Database Backup location
	// Database Backup location
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Database Backup name
	// Database Backup name
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this backup belongs to
	// ID of the project this backup belongs to
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of tags for the Database Backup resource
	// List of tags for the Database Backup resource
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Zone for the Database Backup
	// Zone for the Database Backup
	// +kubebuilder:validation:Required
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// DatabasebackupSpec defines the desired state of Databasebackup
type DatabasebackupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatabasebackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabasebackupInitParameters `json:"initProvider,omitempty"`
}

// DatabasebackupStatus defines the observed state of Databasebackup.
type DatabasebackupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatabasebackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Databasebackup is the Schema for the Databasebackups API. Manages an ArubaCloud Database Backup.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Databasebackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dbaasId) || (has(self.initProvider) && has(self.initProvider.dbaasId))",message="spec.forProvider.dbaasId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DatabasebackupSpec   `json:"spec"`
	Status DatabasebackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabasebackupList contains a list of Databasebackups
type DatabasebackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Databasebackup `json:"items"`
}

// Repository type metadata.
var (
	Databasebackup_Kind             = "Databasebackup"
	Databasebackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Databasebackup_Kind}.String()
	Databasebackup_KindAPIVersion   = Databasebackup_Kind + "." + CRDGroupVersion.String()
	Databasebackup_GroupVersionKind = CRDGroupVersion.WithKind(Databasebackup_Kind)
)

func init() {
	SchemeBuilder.Register(&Databasebackup{}, &DatabasebackupList{})
}
