// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CloudServerInitParameters struct {

	// (String) CloudServer location
	// CloudServer location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) CloudServer name
	// CloudServer name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the cloud server (see below for nested schema)
	Network *NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) Project ID
	// Project ID
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Cloud server settings (see below for nested schema)
	Settings *SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Storage configuration for the cloud server (see below for nested schema)
	Storage *StorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of tags for the Cloud Server
	// List of tags for the Cloud Server
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Zone
	// Zone
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type CloudServerObservation struct {

	// (String) CloudServer identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) CloudServer location
	// CloudServer location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) CloudServer name
	// CloudServer name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the cloud server (see below for nested schema)
	Network *NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// (String) Project ID
	// Project ID
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Cloud server settings (see below for nested schema)
	Settings *SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Storage configuration for the cloud server (see below for nested schema)
	Storage *StorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of tags for the Cloud Server
	// List of tags for the Cloud Server
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) CloudServer URI
	// CloudServer URI
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) Zone
	// Zone
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type CloudServerParameters struct {

	// (String) CloudServer location
	// CloudServer location
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) CloudServer name
	// CloudServer name
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the cloud server (see below for nested schema)
	// +kubebuilder:validation:Required
	Network *NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) Project ID
	// Project ID
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Cloud server settings (see below for nested schema)
	// +kubebuilder:validation:Required
	Settings *SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Storage configuration for the cloud server (see below for nested schema)
	// +kubebuilder:validation:Required
	Storage *StorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of tags for the Cloud Server
	// List of tags for the Cloud Server
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Zone
	// Zone
	// +kubebuilder:validation:Required
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NetworkInitParameters struct {

	// (String) Elastic IP URI reference (e.g., arubacloud_elasticip.example.uri)
	// Elastic IP URI reference (e.g., arubacloud_elasticip.example.uri)
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (List of String) List of security group URI references (e.g., [arubacloud_securitygroup.example.uri])
	// List of security group URI references (e.g., [arubacloud_securitygroup.example.uri])
	SecuritygroupURIRefs []*string `json:"securitygroupUriRefs,omitempty" tf:"securitygroup_uri_refs,omitempty"`

	// (List of String) List of subnet URI references (e.g., [arubacloud_subnet.example.uri])
	// List of subnet URI references (e.g., [arubacloud_subnet.example.uri])
	SubnetURIRefs []*string `json:"subnetUriRefs,omitempty" tf:"subnet_uri_refs,omitempty"`

	// (String) VPC URI reference (e.g., arubacloud_vpc.example.uri)
	// VPC URI reference (e.g., arubacloud_vpc.example.uri)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkObservation struct {

	// (String) Elastic IP URI reference (e.g., arubacloud_elasticip.example.uri)
	// Elastic IP URI reference (e.g., arubacloud_elasticip.example.uri)
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (List of String) List of security group URI references (e.g., [arubacloud_securitygroup.example.uri])
	// List of security group URI references (e.g., [arubacloud_securitygroup.example.uri])
	SecuritygroupURIRefs []*string `json:"securitygroupUriRefs,omitempty" tf:"securitygroup_uri_refs,omitempty"`

	// (List of String) List of subnet URI references (e.g., [arubacloud_subnet.example.uri])
	// List of subnet URI references (e.g., [arubacloud_subnet.example.uri])
	SubnetURIRefs []*string `json:"subnetUriRefs,omitempty" tf:"subnet_uri_refs,omitempty"`

	// (String) VPC URI reference (e.g., arubacloud_vpc.example.uri)
	// VPC URI reference (e.g., arubacloud_vpc.example.uri)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkParameters struct {

	// (String) Elastic IP URI reference (e.g., arubacloud_elasticip.example.uri)
	// Elastic IP URI reference (e.g., arubacloud_elasticip.example.uri)
	// +kubebuilder:validation:Optional
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (List of String) List of security group URI references (e.g., [arubacloud_securitygroup.example.uri])
	// List of security group URI references (e.g., [arubacloud_securitygroup.example.uri])
	// +kubebuilder:validation:Optional
	SecuritygroupURIRefs []*string `json:"securitygroupUriRefs" tf:"securitygroup_uri_refs,omitempty"`

	// (List of String) List of subnet URI references (e.g., [arubacloud_subnet.example.uri])
	// List of subnet URI references (e.g., [arubacloud_subnet.example.uri])
	// +kubebuilder:validation:Optional
	SubnetURIRefs []*string `json:"subnetUriRefs" tf:"subnet_uri_refs,omitempty"`

	// (String) VPC URI reference (e.g., arubacloud_vpc.example.uri)
	// VPC URI reference (e.g., arubacloud_vpc.example.uri)
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef" tf:"vpc_uri_ref,omitempty"`
}

type SettingsInitParameters struct {

	// flavors
	// Flavor name (e.g., CSO4A8 for 4 CPU, 8GB RAM). See https://api.arubacloud.com/docs/metadata/#cloudserver-flavors
	FlavorName *string `json:"flavorName,omitempty" tf:"flavor_name,omitempty"`

	// (String) Key Pair URI reference (e.g., arubacloud_keypair.example.uri)
	// Key Pair URI reference (e.g., arubacloud_keypair.example.uri)
	KeyPairURIRef *string `json:"keyPairUriRef,omitempty" tf:"key_pair_uri_ref,omitempty"`

	// Init user data (raw YAML content)
	// Cloud-Init user data (raw YAML content)
	UserDataSecretRef *v1.LocalSecretKeySelector `json:"userDataSecretRef,omitempty" tf:"-"`
}

type SettingsObservation struct {

	// flavors
	// Flavor name (e.g., CSO4A8 for 4 CPU, 8GB RAM). See https://api.arubacloud.com/docs/metadata/#cloudserver-flavors
	FlavorName *string `json:"flavorName,omitempty" tf:"flavor_name,omitempty"`

	// (String) Key Pair URI reference (e.g., arubacloud_keypair.example.uri)
	// Key Pair URI reference (e.g., arubacloud_keypair.example.uri)
	KeyPairURIRef *string `json:"keyPairUriRef,omitempty" tf:"key_pair_uri_ref,omitempty"`
}

type SettingsParameters struct {

	// flavors
	// Flavor name (e.g., CSO4A8 for 4 CPU, 8GB RAM). See https://api.arubacloud.com/docs/metadata/#cloudserver-flavors
	// +kubebuilder:validation:Optional
	FlavorName *string `json:"flavorName" tf:"flavor_name,omitempty"`

	// (String) Key Pair URI reference (e.g., arubacloud_keypair.example.uri)
	// Key Pair URI reference (e.g., arubacloud_keypair.example.uri)
	// +kubebuilder:validation:Optional
	KeyPairURIRef *string `json:"keyPairUriRef,omitempty" tf:"key_pair_uri_ref,omitempty"`

	// Init user data (raw YAML content)
	// Cloud-Init user data (raw YAML content)
	// +kubebuilder:validation:Optional
	UserDataSecretRef *v1.LocalSecretKeySelector `json:"userDataSecretRef,omitempty" tf:"-"`
}

type StorageInitParameters struct {

	// (String) Boot volume URI reference (e.g., arubacloud_blockstorage.example.uri)
	// Boot volume URI reference (e.g., arubacloud_blockstorage.example.uri)
	BootVolumeURIRef *string `json:"bootVolumeUriRef,omitempty" tf:"boot_volume_uri_ref,omitempty"`
}

type StorageObservation struct {

	// (String) Boot volume URI reference (e.g., arubacloud_blockstorage.example.uri)
	// Boot volume URI reference (e.g., arubacloud_blockstorage.example.uri)
	BootVolumeURIRef *string `json:"bootVolumeUriRef,omitempty" tf:"boot_volume_uri_ref,omitempty"`
}

type StorageParameters struct {

	// (String) Boot volume URI reference (e.g., arubacloud_blockstorage.example.uri)
	// Boot volume URI reference (e.g., arubacloud_blockstorage.example.uri)
	// +kubebuilder:validation:Optional
	BootVolumeURIRef *string `json:"bootVolumeUriRef" tf:"boot_volume_uri_ref,omitempty"`
}

// CloudServerSpec defines the desired state of CloudServer
type CloudServerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CloudServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CloudServerInitParameters `json:"initProvider,omitempty"`
}

// CloudServerStatus defines the observed state of CloudServer.
type CloudServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CloudServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CloudServer is the Schema for the CloudServers API. Manages an ArubaCloud CloudServer.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type CloudServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   CloudServerSpec   `json:"spec"`
	Status CloudServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudServerList contains a list of CloudServers
type CloudServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudServer `json:"items"`
}

// Repository type metadata.
var (
	CloudServer_Kind             = "CloudServer"
	CloudServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CloudServer_Kind}.String()
	CloudServer_KindAPIVersion   = CloudServer_Kind + "." + CRDGroupVersion.String()
	CloudServer_GroupVersionKind = CRDGroupVersion.WithKind(CloudServer_Kind)
)

func init() {
	SchemeBuilder.Register(&CloudServer{}, &CloudServerList{})
}
