// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BlockStorageInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Size of the block storage volume in GiB. Must be a positive integer.
	// Size of the block storage volume in GiB. Must be a positive integer.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Storage type. Accepted values: Standard, Performance.
	// Storage type. Accepted values: `Standard`, `Performance`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type BlockStorageObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Size of the block storage volume in GiB. Must be a positive integer.
	// Size of the block storage volume in GiB. Must be a positive integer.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Storage type. Accepted values: Standard, Performance.
	// Storage type. Accepted values: `Standard`, `Performance`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type BlockStorageParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Required
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	// +kubebuilder:validation:Optional
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Size of the block storage volume in GiB. Must be a positive integer.
	// Size of the block storage volume in GiB. Must be a positive integer.
	// +kubebuilder:validation:Required
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Storage type. Accepted values: Standard, Performance.
	// Storage type. Accepted values: `Standard`, `Performance`.
	// +kubebuilder:validation:Required
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// BlockStorageSpec defines the desired state of BlockStorage
type BlockStorageSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BlockStorageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BlockStorageInitParameters `json:"initProvider,omitempty"`
}

// BlockStorageStatus defines the observed state of BlockStorage.
type BlockStorageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BlockStorageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BlockStorage is the Schema for the BlockStorages API. Manages an ArubaCloud Block Storage volume.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type BlockStorage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sizeGb) || (has(self.initProvider) && has(self.initProvider.sizeGb))",message="spec.forProvider.sizeGb is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   BlockStorageSpec   `json:"spec"`
	Status BlockStorageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BlockStorageList contains a list of BlockStorages
type BlockStorageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BlockStorage `json:"items"`
}

// Repository type metadata.
var (
	BlockStorage_Kind             = "BlockStorage"
	BlockStorage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BlockStorage_Kind}.String()
	BlockStorage_KindAPIVersion   = BlockStorage_Kind + "." + CRDGroupVersion.String()
	BlockStorage_GroupVersionKind = CRDGroupVersion.WithKind(BlockStorage_Kind)
)

func init() {
	SchemeBuilder.Register(&BlockStorage{}, &BlockStorageList{})
}
