apiVersion: securitygroup.arubacloud.m.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: securitygroup/v1alpha1/securitygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    location: ITBG-Bergamo
    name: example-security-group
    projectId: your-project-id
    tags:
    - security
    - example
    vpcId: your-vpc-id
