// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KaaSInitParameters struct {

	// (String) Billing period (Hour, Month, Year)
	// Billing period (Hour, Month, Year)
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) KaaS location
	// KaaS location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) KaaS name
	// KaaS name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the KaaS cluster (see below for nested schema)
	Network *NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project this KaaS resource belongs to
	// ID of the project this KaaS resource belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Kubernetes cluster settings (see below for nested schema)
	Settings *SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (List of String) List of tags for the KaaS resource
	// List of tags for the KaaS resource
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type KaaSObservation struct {

	// (String) Billing period (Hour, Month, Year)
	// Billing period (Hour, Month, Year)
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) KaaS identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) KaaS location
	// KaaS location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Management IP address (available when KaaS is active)
	// Management IP address (available when KaaS is active)
	ManagementIP *string `json:"managementIp,omitempty" tf:"management_ip,omitempty"`

	// (String) KaaS name
	// KaaS name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the KaaS cluster (see below for nested schema)
	Network *NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project this KaaS resource belongs to
	// ID of the project this KaaS resource belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Kubernetes cluster settings (see below for nested schema)
	Settings *SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// (List of String) List of tags for the KaaS resource
	// List of tags for the KaaS resource
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) KaaS URI
	// KaaS URI
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type KaaSParameters struct {

	// (String) Billing period (Hour, Month, Year)
	// Billing period (Hour, Month, Year)
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) KaaS location
	// KaaS location
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) KaaS name
	// KaaS name
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the KaaS cluster (see below for nested schema)
	// +kubebuilder:validation:Required
	Network *NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project this KaaS resource belongs to
	// ID of the project this KaaS resource belongs to
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Kubernetes cluster settings (see below for nested schema)
	// +kubebuilder:validation:Required
	Settings *SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (List of String) List of tags for the KaaS resource
	// List of tags for the KaaS resource
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type NetworkInitParameters struct {

	// (Attributes) Node CIDR configuration (see below for nested schema)
	NodeCidr *NodeCidrInitParameters `json:"nodeCidr,omitempty" tf:"node_cidr,omitempty"`

	// (String) Pod CIDR in CIDR notation (e.g., 10.0.3.0/24)
	// Pod CIDR in CIDR notation (e.g., 10.0.3.0/24)
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// (String) Security group name
	// Security group name
	SecurityGroupName *string `json:"securityGroupName,omitempty" tf:"security_group_name,omitempty"`

	// (String) Subnet URI reference for the KaaS resource (e.g., arubacloud_subnet.example.uri)
	// Subnet URI reference for the KaaS resource (e.g., arubacloud_subnet.example.uri)
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// (String) VPC URI reference for the KaaS resource (e.g., arubacloud_vpc.example.uri)
	// VPC URI reference for the KaaS resource (e.g., arubacloud_vpc.example.uri)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkObservation struct {

	// (Attributes) Node CIDR configuration (see below for nested schema)
	NodeCidr *NodeCidrObservation `json:"nodeCidr,omitempty" tf:"node_cidr,omitempty"`

	// (String) Pod CIDR in CIDR notation (e.g., 10.0.3.0/24)
	// Pod CIDR in CIDR notation (e.g., 10.0.3.0/24)
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// (String) Security group name
	// Security group name
	SecurityGroupName *string `json:"securityGroupName,omitempty" tf:"security_group_name,omitempty"`

	// (String) Subnet URI reference for the KaaS resource (e.g., arubacloud_subnet.example.uri)
	// Subnet URI reference for the KaaS resource (e.g., arubacloud_subnet.example.uri)
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// (String) VPC URI reference for the KaaS resource (e.g., arubacloud_vpc.example.uri)
	// VPC URI reference for the KaaS resource (e.g., arubacloud_vpc.example.uri)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkParameters struct {

	// (Attributes) Node CIDR configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	NodeCidr *NodeCidrParameters `json:"nodeCidr" tf:"node_cidr,omitempty"`

	// (String) Pod CIDR in CIDR notation (e.g., 10.0.3.0/24)
	// Pod CIDR in CIDR notation (e.g., 10.0.3.0/24)
	// +kubebuilder:validation:Optional
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// (String) Security group name
	// Security group name
	// +kubebuilder:validation:Optional
	SecurityGroupName *string `json:"securityGroupName" tf:"security_group_name,omitempty"`

	// (String) Subnet URI reference for the KaaS resource (e.g., arubacloud_subnet.example.uri)
	// Subnet URI reference for the KaaS resource (e.g., arubacloud_subnet.example.uri)
	// +kubebuilder:validation:Optional
	SubnetURIRef *string `json:"subnetUriRef" tf:"subnet_uri_ref,omitempty"`

	// (String) VPC URI reference for the KaaS resource (e.g., arubacloud_vpc.example.uri)
	// VPC URI reference for the KaaS resource (e.g., arubacloud_vpc.example.uri)
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef" tf:"vpc_uri_ref,omitempty"`
}

type NodeCidrInitParameters struct {

	// (String) Node CIDR address in CIDR notation (e.g., 10.0.0.0/24)
	// Node CIDR address in CIDR notation (e.g., 10.0.0.0/24)
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) KaaS name
	// Node CIDR name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type NodeCidrObservation struct {

	// (String) Node CIDR address in CIDR notation (e.g., 10.0.0.0/24)
	// Node CIDR address in CIDR notation (e.g., 10.0.0.0/24)
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) KaaS name
	// Node CIDR name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type NodeCidrParameters struct {

	// (String) Node CIDR address in CIDR notation (e.g., 10.0.0.0/24)
	// Node CIDR address in CIDR notation (e.g., 10.0.0.0/24)
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (String) KaaS name
	// Node CIDR name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type NodePoolsInitParameters struct {

	// (Boolean) Enable autoscaling for node pool
	// Enable autoscaling for node pool
	Autoscaling *bool `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) KaaS flavor name for nodes. Available flavors are described in the ArubaCloud API documentation. For example, K2A4 means 2 CPU, 4GB RAM, and 40GB storage.
	// KaaS flavor name for nodes. Available flavors are described in the [ArubaCloud API documentation](https://api.arubacloud.com/docs/metadata#kaas-flavors). For example, `K2A4` means 2 CPU, 4GB RAM, and 40GB storage.
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (Number) Maximum number of nodes for autoscaling
	// Maximum number of nodes for autoscaling
	MaxCount *float64 `json:"maxCount,omitempty" tf:"max_count,omitempty"`

	// (Number) Minimum number of nodes for autoscaling
	// Minimum number of nodes for autoscaling
	MinCount *float64 `json:"minCount,omitempty" tf:"min_count,omitempty"`

	// (String) KaaS name
	// Node pool name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of nodes in the node pool
	// Number of nodes in the node pool
	Nodes *float64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (String) Datacenter/zone code for nodes
	// Datacenter/zone code for nodes
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NodePoolsObservation struct {

	// (Boolean) Enable autoscaling for node pool
	// Enable autoscaling for node pool
	Autoscaling *bool `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) KaaS flavor name for nodes. Available flavors are described in the ArubaCloud API documentation. For example, K2A4 means 2 CPU, 4GB RAM, and 40GB storage.
	// KaaS flavor name for nodes. Available flavors are described in the [ArubaCloud API documentation](https://api.arubacloud.com/docs/metadata#kaas-flavors). For example, `K2A4` means 2 CPU, 4GB RAM, and 40GB storage.
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (Number) Maximum number of nodes for autoscaling
	// Maximum number of nodes for autoscaling
	MaxCount *float64 `json:"maxCount,omitempty" tf:"max_count,omitempty"`

	// (Number) Minimum number of nodes for autoscaling
	// Minimum number of nodes for autoscaling
	MinCount *float64 `json:"minCount,omitempty" tf:"min_count,omitempty"`

	// (String) KaaS name
	// Node pool name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of nodes in the node pool
	// Number of nodes in the node pool
	Nodes *float64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (String) Datacenter/zone code for nodes
	// Datacenter/zone code for nodes
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NodePoolsParameters struct {

	// (Boolean) Enable autoscaling for node pool
	// Enable autoscaling for node pool
	// +kubebuilder:validation:Optional
	Autoscaling *bool `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) KaaS flavor name for nodes. Available flavors are described in the ArubaCloud API documentation. For example, K2A4 means 2 CPU, 4GB RAM, and 40GB storage.
	// KaaS flavor name for nodes. Available flavors are described in the [ArubaCloud API documentation](https://api.arubacloud.com/docs/metadata#kaas-flavors). For example, `K2A4` means 2 CPU, 4GB RAM, and 40GB storage.
	// +kubebuilder:validation:Optional
	Instance *string `json:"instance" tf:"instance,omitempty"`

	// (Number) Maximum number of nodes for autoscaling
	// Maximum number of nodes for autoscaling
	// +kubebuilder:validation:Optional
	MaxCount *float64 `json:"maxCount,omitempty" tf:"max_count,omitempty"`

	// (Number) Minimum number of nodes for autoscaling
	// Minimum number of nodes for autoscaling
	// +kubebuilder:validation:Optional
	MinCount *float64 `json:"minCount,omitempty" tf:"min_count,omitempty"`

	// (String) KaaS name
	// Node pool name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Number) Number of nodes in the node pool
	// Number of nodes in the node pool
	// +kubebuilder:validation:Optional
	Nodes *float64 `json:"nodes" tf:"nodes,omitempty"`

	// (String) Datacenter/zone code for nodes
	// Datacenter/zone code for nodes
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone" tf:"zone,omitempty"`
}

type SettingsInitParameters struct {

	// (Boolean) High availability
	// High availability
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// (String) Kubernetes version. Available versions are described in the ArubaCloud API documentation. For example, 1.33.2.
	// Kubernetes version. Available versions are described in the [ArubaCloud API documentation](https://api.arubacloud.com/docs/metadata#kubernetes-version). For example, `1.33.2`.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (Attributes List) Node pools configuration (see below for nested schema)
	NodePools []NodePoolsInitParameters `json:"nodePools,omitempty" tf:"node_pools,omitempty"`
}

type SettingsObservation struct {

	// (Boolean) High availability
	// High availability
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// (String) Kubernetes version. Available versions are described in the ArubaCloud API documentation. For example, 1.33.2.
	// Kubernetes version. Available versions are described in the [ArubaCloud API documentation](https://api.arubacloud.com/docs/metadata#kubernetes-version). For example, `1.33.2`.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (Attributes List) Node pools configuration (see below for nested schema)
	NodePools []NodePoolsObservation `json:"nodePools,omitempty" tf:"node_pools,omitempty"`
}

type SettingsParameters struct {

	// (Boolean) High availability
	// High availability
	// +kubebuilder:validation:Optional
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// (String) Kubernetes version. Available versions are described in the ArubaCloud API documentation. For example, 1.33.2.
	// Kubernetes version. Available versions are described in the [ArubaCloud API documentation](https://api.arubacloud.com/docs/metadata#kubernetes-version). For example, `1.33.2`.
	// +kubebuilder:validation:Optional
	KubernetesVersion *string `json:"kubernetesVersion" tf:"kubernetes_version,omitempty"`

	// (Attributes List) Node pools configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	NodePools []NodePoolsParameters `json:"nodePools" tf:"node_pools,omitempty"`
}

// KaaSSpec defines the desired state of KaaS
type KaaSSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KaaSParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KaaSInitParameters `json:"initProvider,omitempty"`
}

// KaaSStatus defines the observed state of KaaS.
type KaaSStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KaaSObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KaaS is the Schema for the KaaSs API. Manages an ArubaCloud Kubernetes as a Service (KaaS) cluster. Once the cluster is ready, the provider downloads and exposes the kubeconfig (decoded from the API) so you can use it with kubectl or write it to a file.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,arubacloud},path=kaas
type KaaS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	Spec   KaaSSpec   `json:"spec"`
	Status KaaSStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KaaSList contains a list of KaaSs
type KaaSList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KaaS `json:"items"`
}

// Repository type metadata.
var (
	KaaS_Kind             = "KaaS"
	KaaS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KaaS_Kind}.String()
	KaaS_KindAPIVersion   = KaaS_Kind + "." + CRDGroupVersion.String()
	KaaS_GroupVersionKind = CRDGroupVersion.WithKind(KaaS_Kind)
)

func init() {
	SchemeBuilder.Register(&KaaS{}, &KaaSList{})
}
