// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type VPCPeeringInitParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	PeerVPC *string `json:"peerVpc,omitempty" tf:"peer_vpc,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type VPCPeeringObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	PeerVPC *string `json:"peerVpc,omitempty" tf:"peer_vpc,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type VPCPeeringParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	// +kubebuilder:validation:Required
	PeerVPC *string `json:"peerVpc,omitempty" tf:"peer_vpc,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	// +kubebuilder:validation:Required
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

// VPCPeeringSpec defines the desired state of VPCPeering
type VPCPeeringSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VPCPeeringParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPCPeeringInitParameters `json:"initProvider,omitempty"`
}

// VPCPeeringStatus defines the observed state of VPCPeering.
type VPCPeeringStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VPCPeeringObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPCPeering is the Schema for the VPCPeerings API. Manages an ArubaCloud VPC Peering connection between two VPCs, enabling private routing between them.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,arubacloud}
type VPCPeering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.peerVpc) || (has(self.initProvider) && has(self.initProvider.peerVpc))",message="spec.forProvider.peerVpc is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcId) || (has(self.initProvider) && has(self.initProvider.vpcId))",message="spec.forProvider.vpcId is a required parameter"
	Spec   VPCPeeringSpec   `json:"spec"`
	Status VPCPeeringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPCPeeringList contains a list of VPCPeerings
type VPCPeeringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCPeering `json:"items"`
}

// Repository type metadata.
var (
	VPCPeering_Kind             = "VPCPeering"
	VPCPeering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPCPeering_Kind}.String()
	VPCPeering_KindAPIVersion   = VPCPeering_Kind + "." + CRDGroupVersion.String()
	VPCPeering_GroupVersionKind = CRDGroupVersion.WithKind(VPCPeering_Kind)
)

func init() {
	SchemeBuilder.Register(&VPCPeering{}, &VPCPeeringList{})
}
