// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AutoscalingInitParameters struct {

	// (Number) Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the step_size amount.
	// Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the `step_size` amount.
	AvailableSpace *float64 `json:"availableSpace,omitempty" tf:"available_space,omitempty"`

	// (Boolean) Whether storage autoscaling is enabled.
	// Whether storage autoscaling is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Amount of storage (in GB) added on each autoscaling event.
	// Amount of storage (in GB) added on each autoscaling event.
	StepSize *float64 `json:"stepSize,omitempty" tf:"step_size,omitempty"`
}

type AutoscalingObservation struct {

	// (Number) Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the step_size amount.
	// Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the `step_size` amount.
	AvailableSpace *float64 `json:"availableSpace,omitempty" tf:"available_space,omitempty"`

	// (Boolean) Whether storage autoscaling is enabled.
	// Whether storage autoscaling is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Amount of storage (in GB) added on each autoscaling event.
	// Amount of storage (in GB) added on each autoscaling event.
	StepSize *float64 `json:"stepSize,omitempty" tf:"step_size,omitempty"`
}

type AutoscalingParameters struct {

	// (Number) Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the step_size amount.
	// Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the `step_size` amount.
	// +kubebuilder:validation:Optional
	AvailableSpace *float64 `json:"availableSpace" tf:"available_space,omitempty"`

	// (Boolean) Whether storage autoscaling is enabled.
	// Whether storage autoscaling is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (Number) Amount of storage (in GB) added on each autoscaling event.
	// Amount of storage (in GB) added on each autoscaling event.
	// +kubebuilder:validation:Optional
	StepSize *float64 `json:"stepSize" tf:"step_size,omitempty"`
}

type DBaaSInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year. If omitted, the value returned by the API is used (Computed).
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`. If omitted, the value returned by the API is used (Computed).
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// 8.0 for MySQL 8.0, postgresql-15 for PostgreSQL 15). See the available engines. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Database engine type and version identifier (e.g., `mysql-8.0` for MySQL 8.0, `postgresql-15` for PostgreSQL 15). See the [available engines](https://api.arubacloud.com/docs/metadata/#dbaas-engines). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// (String) Compute flavour for the DBaaS cluster nodes. See available flavours. For example, DBO2A4 means 2 vCPU and 4 GB RAM.
	// Compute flavour for the DBaaS cluster nodes. See [available flavours](https://api.arubacloud.com/docs/metadata/#dbaas-flavors). For example, `DBO2A4` means 2 vCPU and 4 GB RAM.
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the DBaaS cluster.
	// Display name for the DBaaS cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the DBaaS instance. All URI references are immutable after creation. (see below for nested schema)
	Network *NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Storage configuration for the DBaaS instance. (see below for nested schema)
	Storage *StorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Availability zone within the region where the DBaaS cluster is deployed. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBaaSObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year. If omitted, the value returned by the API is used (Computed).
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`. If omitted, the value returned by the API is used (Computed).
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// 8.0 for MySQL 8.0, postgresql-15 for PostgreSQL 15). See the available engines. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Database engine type and version identifier (e.g., `mysql-8.0` for MySQL 8.0, `postgresql-15` for PostgreSQL 15). See the [available engines](https://api.arubacloud.com/docs/metadata/#dbaas-engines). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// (String) Compute flavour for the DBaaS cluster nodes. See available flavours. For example, DBO2A4 means 2 vCPU and 4 GB RAM.
	// Compute flavour for the DBaaS cluster nodes. See [available flavours](https://api.arubacloud.com/docs/metadata/#dbaas-flavors). For example, `DBO2A4` means 2 vCPU and 4 GB RAM.
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the DBaaS cluster.
	// Display name for the DBaaS cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the DBaaS instance. All URI references are immutable after creation. (see below for nested schema)
	Network *NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Storage configuration for the DBaaS instance. (see below for nested schema)
	Storage *StorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// created.)
	// Availability zone within the region where the DBaaS cluster is deployed. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBaaSParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year. If omitted, the value returned by the API is used (Computed).
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`. If omitted, the value returned by the API is used (Computed).
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// 8.0 for MySQL 8.0, postgresql-15 for PostgreSQL 15). See the available engines. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Database engine type and version identifier (e.g., `mysql-8.0` for MySQL 8.0, `postgresql-15` for PostgreSQL 15). See the [available engines](https://api.arubacloud.com/docs/metadata/#dbaas-engines). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Required
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// (String) Compute flavour for the DBaaS cluster nodes. See available flavours. For example, DBO2A4 means 2 vCPU and 4 GB RAM.
	// Compute flavour for the DBaaS cluster nodes. See [available flavours](https://api.arubacloud.com/docs/metadata/#dbaas-flavors). For example, `DBO2A4` means 2 vCPU and 4 GB RAM.
	// +kubebuilder:validation:Required
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Required
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the DBaaS cluster.
	// Display name for the DBaaS cluster.
	// +kubebuilder:validation:Required
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the DBaaS instance. All URI references are immutable after creation. (see below for nested schema)
	// +kubebuilder:validation:Required
	Network *NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Storage configuration for the DBaaS instance. (see below for nested schema)
	// +kubebuilder:validation:Required
	Storage *StorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Availability zone within the region where the DBaaS cluster is deployed. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Required
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NetworkInitParameters struct {

	// (String) Optional URI reference to an Elastic IP resource.
	// Optional URI reference to an Elastic IP resource.
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (String) URI reference to the Security Group resource.
	// URI reference to the Security Group resource.
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// (String) URI reference to the Subnet resource.
	// URI reference to the Subnet resource.
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// (String) URI reference to the VPC resource.
	// URI reference to the VPC resource.
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkObservation struct {

	// (String) Optional URI reference to an Elastic IP resource.
	// Optional URI reference to an Elastic IP resource.
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (String) URI reference to the Security Group resource.
	// URI reference to the Security Group resource.
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// (String) URI reference to the Subnet resource.
	// URI reference to the Subnet resource.
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// (String) URI reference to the VPC resource.
	// URI reference to the VPC resource.
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkParameters struct {

	// (String) Optional URI reference to an Elastic IP resource.
	// Optional URI reference to an Elastic IP resource.
	// +kubebuilder:validation:Optional
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (String) URI reference to the Security Group resource.
	// URI reference to the Security Group resource.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRef *string `json:"securityGroupUriRef" tf:"security_group_uri_ref,omitempty"`

	// (String) URI reference to the Subnet resource.
	// URI reference to the Subnet resource.
	// +kubebuilder:validation:Optional
	SubnetURIRef *string `json:"subnetUriRef" tf:"subnet_uri_ref,omitempty"`

	// (String) URI reference to the VPC resource.
	// URI reference to the VPC resource.
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef" tf:"vpc_uri_ref,omitempty"`
}

type StorageInitParameters struct {

	// (Attributes) Optional autoscaling configuration for the DBaaS storage. (see below for nested schema)
	Autoscaling *AutoscalingInitParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) Storage size in GB for the DBaaS instance.
	// Storage size in GB for the DBaaS instance.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`
}

type StorageObservation struct {

	// (Attributes) Optional autoscaling configuration for the DBaaS storage. (see below for nested schema)
	Autoscaling *AutoscalingObservation `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) Storage size in GB for the DBaaS instance.
	// Storage size in GB for the DBaaS instance.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`
}

type StorageParameters struct {

	// (Attributes) Optional autoscaling configuration for the DBaaS storage. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Autoscaling *AutoscalingParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) Storage size in GB for the DBaaS instance.
	// Storage size in GB for the DBaaS instance.
	// +kubebuilder:validation:Optional
	SizeGb *float64 `json:"sizeGb" tf:"size_gb,omitempty"`
}

// DBaaSSpec defines the desired state of DBaaS
type DBaaSSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DBaaSParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DBaaSInitParameters `json:"initProvider,omitempty"`
}

// DBaaSStatus defines the observed state of DBaaS.
type DBaaSStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DBaaSObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DBaaS is the Schema for the DBaaSs API. Manages an ArubaCloud DBaaS cluster — a managed database cluster with automated backups and high availability.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,arubacloud},path=dbaas
type DBaaS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engineId) || (has(self.initProvider) && has(self.initProvider.engineId))",message="spec.forProvider.engineId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.flavor) || (has(self.initProvider) && has(self.initProvider.flavor))",message="spec.forProvider.flavor is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DBaaSSpec   `json:"spec"`
	Status DBaaSStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DBaaSList contains a list of DBaaSs
type DBaaSList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBaaS `json:"items"`
}

// Repository type metadata.
var (
	DBaaS_Kind             = "DBaaS"
	DBaaS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DBaaS_Kind}.String()
	DBaaS_KindAPIVersion   = DBaaS_Kind + "." + CRDGroupVersion.String()
	DBaaS_GroupVersionKind = CRDGroupVersion.WithKind(DBaaS_Kind)
)

func init() {
	SchemeBuilder.Register(&DBaaS{}, &DBaaSList{})
}
