// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SnapshotInitParameters struct {

	// (String) Billing period (only 'Hour' allowed)
	// Billing period (only 'Hour' allowed)
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Snapshot location
	// Snapshot location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Snapshot name
	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this Snapshot belongs to
	// ID of the project this Snapshot belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of tags for the snapshot
	// List of tags for the snapshot
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) URI of the volume this snapshot is for. Should be the volume URI (e.g., /projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}). You can reference the uri attribute from an arubacloud_blockstorage resource.
	// URI of the volume this snapshot is for. Should be the volume URI (e.g., `/projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}`). You can reference the `uri` attribute from an `arubacloud_blockstorage` resource.
	VolumeURI *string `json:"volumeUri,omitempty" tf:"volume_uri,omitempty"`
}

type SnapshotObservation struct {

	// (String) Billing period (only 'Hour' allowed)
	// Billing period (only 'Hour' allowed)
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Snapshot identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Snapshot location
	// Snapshot location
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Snapshot name
	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this Snapshot belongs to
	// ID of the project this Snapshot belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of tags for the snapshot
	// List of tags for the snapshot
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Snapshot URI
	// Snapshot URI
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) URI of the volume this snapshot is for. Should be the volume URI (e.g., /projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}). You can reference the uri attribute from an arubacloud_blockstorage resource.
	// URI of the volume this snapshot is for. Should be the volume URI (e.g., `/projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}`). You can reference the `uri` attribute from an `arubacloud_blockstorage` resource.
	VolumeURI *string `json:"volumeUri,omitempty" tf:"volume_uri,omitempty"`
}

type SnapshotParameters struct {

	// (String) Billing period (only 'Hour' allowed)
	// Billing period (only 'Hour' allowed)
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Snapshot location
	// Snapshot location
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Snapshot name
	// Snapshot name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project this Snapshot belongs to
	// ID of the project this Snapshot belongs to
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of tags for the snapshot
	// List of tags for the snapshot
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) URI of the volume this snapshot is for. Should be the volume URI (e.g., /projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}). You can reference the uri attribute from an arubacloud_blockstorage resource.
	// URI of the volume this snapshot is for. Should be the volume URI (e.g., `/projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}`). You can reference the `uri` attribute from an `arubacloud_blockstorage` resource.
	// +kubebuilder:validation:Optional
	VolumeURI *string `json:"volumeUri,omitempty" tf:"volume_uri,omitempty"`
}

// SnapshotSpec defines the desired state of Snapshot
type SnapshotSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SnapshotParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SnapshotInitParameters `json:"initProvider,omitempty"`
}

// SnapshotStatus defines the observed state of Snapshot.
type SnapshotStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SnapshotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Snapshot is the Schema for the Snapshots API. Manages an ArubaCloud Snapshot.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Snapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.volumeUri) || (has(self.initProvider) && has(self.initProvider.volumeUri))",message="spec.forProvider.volumeUri is a required parameter"
	Spec   SnapshotSpec   `json:"spec"`
	Status SnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SnapshotList contains a list of Snapshots
type SnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Snapshot `json:"items"`
}

// Repository type metadata.
var (
	Snapshot_Kind             = "Snapshot"
	Snapshot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Snapshot_Kind}.String()
	Snapshot_KindAPIVersion   = Snapshot_Kind + "." + CRDGroupVersion.String()
	Snapshot_GroupVersionKind = CRDGroupVersion.WithKind(Snapshot_Kind)
)

func init() {
	SchemeBuilder.Register(&Snapshot{}, &SnapshotList{})
}
