apiVersion: vpntunnel.arubacloud.m.crossplane.io/v1alpha1
kind: VPNTunnel
metadata:
  annotations:
    meta.upbound.io/example-id: vpntunnel/v1alpha1/vpntunnel
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    location: ITBG-Bergamo
    name: example-vpn-tunnel
    projectId: your-project-id
    properties:
      vpnClientProtocol: ikev2
      vpnType: Site-To-Site
